version: '3.7'

services:
  client:
    build: clients/angular
    depends_on:
      - api
    ports:
      - 5001:80
    networks:
      - ctdig

  api:
    build: server
    depends_on:
      - mongo
      - rabbitmq
    ports:
    - 5002:80
    networks:
      - ctdig
    environment:
      - "mongoConnection__server=mongodb://mongo:27017/ctdig"
      - "rabbitmq__uri=amqp://guest:guest@rabbitmq:5672/rabbitmq-ctdig"

  mongo:
    image: mongo:latest
    ports:
    - 27018:27017
    networks:
      - ctdig

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 5673:5672
    - 15673:15672
    networks:
      - ctdig
    environment:
      RABBITMQ_DEFAULT_VHOST: rabbitmq-ctdig

networks:
  ctdig: